In [1]:
# prototyping a 2d random walk code.

In [7]:
from collections import namedtuple
import numpy as np
from rvi_sampling.utils import stochastic_processes
from rvi_sampling.stochastic_processes.random_walk import RWParameters

In [8]:
rwargs = namedtuple('rwargs', 'rw_width rw_time rw_seed')
args = rwargs(5, 50, 0)

DIMENSIONS = 2
ACTION_PROB = np.ones(4) / 4.0
ACTIONS = [[-1, 0], [0, -1], [0, +1], [+1, 0]]
bias = RWParameters(ACTIONS, ACTION_PROB, DIMENSIONS)

rw, analytic = stochastic_processes.create_rw(
    args=args,
    biased=bias,
    n_agents=10)

In [39]:
start_dist = [rw.simulate()[0] for _ in range(10000)]

In [41]:
np.stack(start_dist).max(0)

array([5, 5])

In [42]:
np.stack(start_dist).min(0)

array([-5, -5])

In [43]:
np.stack(start_dist).mean(0)

array([-0.0352, -0.0096])